In [1]:
import numpy as np
print('Numpy Version : {:s}'.format(np.__version__))
import matplotlib
print('MatPlotLib Version : {:s}'.format(matplotlib.__version__))
import matplotlib.pyplot as plt

Numpy Version : 1.14.3
MatPlotLib Version : 2.2.2


# 배열의 연산

### 벡터화 연산
* 벡터화 연산을 쓰면 명시적으로 반복문을 사용하지 않고 반복 연산을 할 수 있다.
* 간단하게 선형 대수 공식과 동일한 코드를 작성할 수 있다.

* `%%time` : 셀 코드의 실행 시간을 측정하는 IPython 매직 명령이다.

In [3]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [4]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: user 12.7 ms, sys: 2.49 ms, total: 15.2 ms
Wall time: 23.4 ms


In [5]:
%%time
z = x + y

CPU times: user 616 µs, sys: 572 µs, total: 1.19 ms
Wall time: 599 µs


** 사칙 연산뿐 아니라 비교 연산과 같은 논리 연산도 가능하다 **

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [7]:
a == b

array([False,  True, False,  True])

In [8]:
a >= b

array([False,  True,  True,  True])

* `all` : 배열의 모든 원소가 다 같은지 알아낸다.

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [11]:
np.all(a == b)

False

In [12]:
np.all(a == c)

True

* `exp` : 지수 함수
* `log` : 로그 함수

In [13]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [14]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
10 ** a

array([    1,    10,   100,  1000, 10000])

In [16]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

### 브로드캐스팅
* 벡터끼리 연산을 처리하려면 두 벡터의 크기가 같아야한다.
* Numpy에서는 서로 다른 크기를 가진 두 배열의 사칙 연산도 지원한다.
* `브로드캐스팅(broadcasting)` : 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법

In [17]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [18]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [19]:
x + y

array([1, 2, 3, 4, 5])

In [20]:
x + 1

array([1, 2, 3, 4, 5])

** 브로드캐스팅은 더 차원이 높은 경우에도 적용된다.**

In [21]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [22]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [24]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [25]:
y = np.arange(3)
y

array([0, 1, 2])

In [26]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

### 차원 축소 연산
* `차원 축소(dimension reduction)` : 행렬의 하나의 행에 있는 원소들의 평균을 구하면 각 행에 대해 하나의 숫자가 나오게된다.
* NumPy는 다음과 같은 차원 축소 연산 명령 혹은 메서드를 지원한다.
    * 최대/최소: min, max, argmin, argmax
    * 통계: sum, mean, median, std, var
    * 불리언: all, any

In [27]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [28]:
np.sum(x)

10

In [29]:
x.sum()

10

In [30]:
x = np.array([1, 3, 2])

In [31]:
x.min()

1

In [35]:
x.argmin() # 최솟값의 위치

0

In [34]:
x.argmax()  # 최댓값의 위치

1

In [36]:
x = np.array([1, 2, 3, 1])

In [37]:
x.mean()

1.75

In [38]:
np.median(x)

1.5

In [39]:
np.all([True, True, False])

False

In [40]:
np.any([True, True, False])

True

* `axis` : 어느 차원으로 계산 할지를 정함 (0 : 열 연산 , 1 : 행 연산)

In [42]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [43]:
x.sum()

6

In [44]:
x.sum(axis=0)   # 열 합계

array([3, 3])

In [45]:
x.sum(axis=1)   # 행 합계

array([2, 4])

### 정렬
* `sort` : 배열 안의 원소를 크기에 따라 정렬한다.(axis 인수를 사용하여 차원을 선택할 수 있다.)

In [46]:
a = np.array([[4,  3,  5,  7], 
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [47]:
np.sort(a)  # axis=-1 또는 axis=1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [48]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [49]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

** 만약 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort 명령을 사용한다. **

In [50]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [51]:
a[j]

array([12, 25, 38, 42])

In [52]:
np.sort(a)

array([12, 25, 38, 42])